### ISSUE TITLE
Datetime fails on modern 2.10

### ISSUE THREAD

**Issue by DifferentialOrange** [igorcoding/asynctnt#29]
Tests fails in CI with Tarantool 2.10.1

```
ERROR: test__ext_datetime_write_before_1970 (test_mp_ext.MpExtTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/asynctnt/asynctnt/asynctnt/_testbase.py", line 67, in wrapper
    self.loop.run_until_complete(__meth__(self, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/work/asynctnt/asynctnt/asynctnt/_testbase.py", line 293, in wrap
    return await res
  File "/home/runner/work/asynctnt/asynctnt/tests/test_mp_ext.py", line 223, in test__ext_datetime_write_before_1970
    resp = await self.conn.insert(sp, [1, dt])
asynctnt.exceptions.TarantoolDatabaseError: Invalid MsgPack - packet body
```

See https://github.com/DifferentialOrange/asynctnt/runs/7879026191?check_suite_focus=true

**Comment by igorcoding** [comment]
Thank you. I see the problem, will work on the solution
