### ISSUE TITLE
Auto-reconnect does not work

### ISSUE THREAD

**Issue by bofm** [igorcoding/asynctnt#6]
Code:
```python
import asyncio
import asynctnt
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


async def run():
    c = asynctnt.Connection(host='localhost', port=33301)
    await c.connect()
    while 1:
        await c.call('box.info')   # <-- Tarantool instance goes down here

loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(run())
except KeyboardInterrupt:
    loop.stop()
    loop.close()
```
Error:
```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    loop.run_until_complete(run())
  File "uvloop/loop.pyx", line 1364, in uvloop.loop.Loop.run_until_complete
  File "app.py", line 11, in run
    await c.call('box.info')
  File "asynctnt/iproto/db.pyx", line 31, in execute (asynctnt/iproto/protocol.c:19633)
asynctnt.exceptions.TarantoolNotConnectedError: Lost connection to Tarantool
```
Environment:
```
Python 3.6.4
MacOS 10.13.3

asynctnt==0.1.11
uvloop==0.9.1
```

**Comment by igorcoding** [comment]
Thank you for the report, but it's actually an intended behaviour. The main idea idea is to better fail if connection is lost than hang the request trying to connect indefinitely to Tarantool. Take a look at the following script:

```python
import asyncio
import asynctnt
import asynctnt.exceptions
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())


async def run():
    c = asynctnt.Connection(host='localhost', port=33301)
    await c.connect()
    while 1:
        try:
            print(await c.call('box.info'))   # <-- Tarantool instance goes down here
        except asynctnt.exceptions.TarantoolNotConnectedError:
            print('lost connection')
        await asyncio.sleep(1)


loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(run())
except KeyboardInterrupt:
    loop.stop()
    loop.close()

```

If you run it you will see messages like 
```
Connect to Tarantool[localhost:33301] failed: ConnectionRefusedError(111, 'Connection refused'). Retrying in 0.333333 seconds
```

as asynctnt will try to reconnect to Tarntool in the background.And finally when you start Tarantool instance back it will continue to successfully execute `call` statements.

**Comment by bofm** [comment]
I get it. Sorry for bothering.
